### ISSUE TITLE
Java8 Fallback is not working

### ISSUE THREAD

**Issue by katta524** [OWASP/java-html-sanitizer#349]
We are trying to use OWASP Sanitizer for JDK 8 Environment 

Fallback mechanism in Java8Shim constructor is not working.
<1> <2024-10-14T04:41:34Z> <ERROR> <Exception [java.lang.ClassNotFoundException: org.owasp.shim.ForJava9AndLater]
    at org.owasp.shim.Java8Shim.<clinit>(Java8Shim.java:27)
    at org.owasp.html.HtmlPolicyBuilder.<clinit>(HtmlPolicyBuilder.java:168)
    at micros.opera.common.generic.utl.sec.htmlsanitization.HtmlSanitizerUtil.removeAllHtmlTags(HtmlSanitizerUtil.java:207)

**Comment by katta524** [comment]
Duplicate of Issue 338
